name = "wish-kaleb-one"
compatibility_date = "2024-12-01"
pages_build_output_dir = "./dist"

[vars]
ALLOWED_EMAILS = "melindajean16@gmail.com,kaleb.bays@gmail.com"
GITHUB_VAULT_REPO = "triursa/second-brain-vault"
GITHUB_VAULT_PATH = "domains/wishlist/BACKLOG.md"
GITHUB_VAULT_BRANCH = "master"

[[d1_databases]]
binding = "DB"
database_name = "wish-kaleb-one-db"
database_id = "0c82412b-b9a4-4a33-9bbf-cb4738c6ce4f"